modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL="https://github.com/Resourceful-Bees/ResoucefulLib/issues/new/choose"

[[mods]]
    modId = "resourcefullib"
    version = "${version}"
    displayName = "Resourceful Lib"
    authors = "ThatGravyBoat"
    description = "Team Resourceful Library"

[[dependencies.resourcefullib]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.resourcefullib]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"